# Generated by Django 5.2.7 on 2025-11-04 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_pub', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CateEducativa',
            fields=[
                ('id_cate_edu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('desc_puntos', models.CharField(blank=True, max_length=50, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JuegoAlternativa',
            fields=[
                ('id_alt', models.AutoField(primary_key=True, serialize=False)),
                ('alternativa_txt', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=100)),
                ('dia_sem', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_ini', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('polyline_encoded', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoResiduo',
            fields=[
                ('id_tipo_res', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telf', models.CharField(blank=True, max_length=15, null=True)),
                ('pts_acum', models.IntegerField(default=0)),
                ('modo_viaje', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('ciudadano', 'Ciudadano'), ('recolector', 'Recolector'), ('admin', 'Admin')], default='ciudadano', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ArtiEducativo',
            fields=[
                ('id_art_edu', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_post', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('img_portada', models.CharField(blank=True, max_length=255, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(db_column='id_cate_edu', on_delete=django.db.models.deletion.RESTRICT, to='api.cateeducativa')),
            ],
        ),
        migrations.CreateModel(
            name='HistoJuego',
            fields=[
                ('id_hist_juego', models.AutoField(primary_key=True, serialize=False)),
                ('pts_ganados_total', models.IntegerField()),
                ('fecha_juego', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('juego', models.ForeignKey(db_column='id_juego', on_delete=django.db.models.deletion.CASCADE, to='api.juego')),
            ],
        ),
        migrations.CreateModel(
            name='HistoRespuesta',
            fields=[
                ('id_hist_resp', models.AutoField(primary_key=True, serialize=False)),
                ('hist_juego', models.ForeignKey(db_column='id_hist_juego', on_delete=django.db.models.deletion.CASCADE, to='api.histojuego')),
                ('alt_elegida', models.ForeignKey(db_column='id_alt_elegida', on_delete=django.db.models.deletion.CASCADE, to='api.juegoalternativa')),
            ],
        ),
        migrations.CreateModel(
            name='JuegoPregunta',
            fields=[
                ('id_preg', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_txt', models.TextField()),
                ('pts_otorga', models.IntegerField(default=10)),
                ('juego', models.ForeignKey(db_column='id_juego', on_delete=django.db.models.deletion.CASCADE, to='api.juego')),
            ],
        ),
        migrations.AddField(
            model_name='juegoalternativa',
            name='pregunta',
            field=models.ForeignKey(db_column='id_preg', on_delete=django.db.models.deletion.CASCADE, to='api.juegopregunta'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id_recompensa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('costo_pts', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='chk_stock_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id_canje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('costo_pts', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recompensa', models.ForeignKey(db_column='id_recompensa', on_delete=django.db.models.deletion.RESTRICT, to='api.recompensa')),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id_camion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lat_act', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lon_act', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estado', models.CharField(choices=[('en_ruta', 'En Ruta'), ('en_base', 'En Base'), ('mantenimiento', 'Mantenimiento')], default='en_base', max_length=15)),
                ('indice_punto', models.IntegerField(default=0)),
                ('esta_activo', models.BooleanField(default=True)),
                ('ruta_actual', models.ForeignKey(blank=True, db_column='id_ruta_act', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='sector',
            field=models.ForeignKey(db_column='id_sector', on_delete=django.db.models.deletion.RESTRICT, to='api.sector'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('descrip', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('es_principal', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRecojo',
            fields=[
                ('id_solic', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solic', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15)),
                ('descrip', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipo_residuo',
            field=models.ForeignKey(db_column='id_tipo_res', on_delete=django.db.models.deletion.RESTRICT, to='api.tiporesiduo'),
        ),
        migrations.CreateModel(
            name='HistoRecol',
            fields=[
                ('id_recol', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntos_otorgados', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_residuo', models.ForeignKey(db_column='id_tipo_res', on_delete=django.db.models.deletion.RESTRICT, to='api.tiporesiduo')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_disp', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='idx_token_pref')],
            },
        ),
        migrations.CreateModel(
            name='EstadoRecojo',
            fields=[
                ('id_est_recojo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('listo', 'Listo'), ('sin_residuos', 'Sin Residuos'), ('en_viaje', 'En Viaje')], default='listo', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fecha')},
            },
        ),
    ]
