# Generated by Django 5.2.7 on 2025-11-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personalmunicipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
